### PR TITLE
Fix bug that SAVE button at admin account form is not enabled when using the same username

### LINKED ISSUE #2208: Unable to update only password of admin account
**What happened**:

It seems there was a frontend bug while updating the admin account at the settings page.
The "SAVE" button is only activated if the given value in the "username" field is different from the current one.

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #2208

**Does this PR introduce a user-facing change?**:

```release-note
Fix bug that SAVE button at admin account form is not enabled when using the same username
```

### CODE REVIEW

File: pkg/app/web/src/components/settings-page/project/components/static-admin-form/index.tsx [hunk 1]
```diff
@@ -102,7 +103,7 @@ const StaticAdminDialog: FC<{
             color="primary"
             disabled={
               formik.isValid === false ||
-              formik.values.username === currentUsername
+              formik.values.username === ""
```
Comment (kurochan) [inline pkg/app/web/src/components/settings-page/project/components/static-admin-form/index.tsx:106]:
```suggestion
```
I think this line is unnecessary because already validated here.
https://github.com/pipe-cd/pipe/pull/2209/files#diff-0e1fa1872588c27aac2a8c319a43642fd2a980e41ced4719c3d2c96fc00ac622R43

Comment (nghialv) [reply pkg/app/web/src/components/settings-page/project/components/static-admin-form/index.tsx:106]: You are totally right! Let me remove this line.

Comment (nakabonne) [reply pkg/app/web/src/components/settings-page/project/components/static-admin-form/index.tsx:106]: For sure!

**Comment by nakabonne** [comment]
Nice
/lgtm

**Comment by khanhtc1202** [comment]
Nice catch
/approve
