### PR TITLE
Fix TTL for stat metrics is reset on stat commit

### LINKED ISSUE #2234: Ensure piped stat metrics is remove from stat cache after piped has stopped
**What would you like to be added**:

**Why is this needed**:

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

Currently, while storing new committed stat from pipeds, Redis `EXPIRE` is always called that reset the TTL set for the stat metrics hash key, lead to piped stat metrics keep available even after piped has stopped.

```
127.0.0.1:6379> TTL HASHKEY:PIPED:STATS
(integer) 266
127.0.0.1:6379> TTL HASHKEY:PIPED:STATS
(integer) 300                    /// TTL is reset here 👀
127.0.0.1:6379> TTL HASHKEY:PIPED:STATS
(integer) 299
```

**Which issue(s) this PR fixes**:

Fixes #2234 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/cache/rediscache/hashcache.go [hunk 1]
```diff
@@ -68,7 +68,22 @@ func (r *RedisHashCache) Put(k string, v interface{}) error {
...
+		return nil
+	}
+
+	rep, err := redigo.Int(conn.Do("TTL", r.key))
+	if err != nil {
+		return err
+	}
+	// Only set TTL for hashkey in case TTL command return key has no TTL.
+	// ref: https://redis.io/commands/TTL
+	if rep < 0 {
```
Comment (nghialv) [inline pkg/cache/rediscache/hashcache.go:86]: Could you add a comment about the TTL behavior for `NewTTLHashCache` function?
Because that TTL will be applied for the whole key instead of each individual field of the key.

**Comment by nghialv** [comment]
I see. I think this way is acceptable in case there are a large number of Pipeds (e.g. our prod env). (The more Pipeds, the lower the "not-found" rate.)
Btw, let's see how the graph will be in our dev environment where only a few Pipeds are running.

File: pkg/cache/rediscache/hashcache.go (hunk 1 above)
Comment (khanhtc1202) [reply pkg/cache/rediscache/hashcache.go:91]: Addressed by https://github.com/pipe-cd/pipe/pull/2235/commits/e1e2a2722130dd35367c576ab50a3ce2de075eb6 🙏

**Comment by nakabonne** [comment]
👍 
/approve
