### PR TITLE
Fix the bug that cancelling a planning deployment causes the piped to be blocked

### LINKED ISSUE #934: Avoid the deployment to get stuck in its queue
**What happened**:

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### LINKED ISSUE #972: Unable to cancel the planning deployment
**What happened**:

The deployment status is still `0`.

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by nghialv**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #972 
Fixes #934

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

/cc @nakabonne

### CODE REVIEW

File: pkg/app/piped/controller/planner.go [hunk 1]
```diff
@@ -97,6 +97,7 @@ func newPlanner(
 		pipedConfig:              pipedConfig,
 		plannerRegistry:          registry.DefaultRegistry(),
 		appManifestsCache:        appManifestsCache,
+		cancelledCh:              make(chan *model.ReportableCommand, 1),
```
Comment (nakabonne) [inline pkg/app/piped/controller/planner.go:100]: I'm very curious about why using buffered-channel. Is there something wrong to use an unbuffered channel with zero capacity?

Comment (nakabonne) [reply pkg/app/piped/controller/planner.go:100]: Fine, I'm getting get it.

Comment (nakabonne) [reply pkg/app/piped/controller/planner.go:100]: This is for preventing the `Cancel()` from being blocked until Run handles the channel, right?
https://github.com/pipe-cd/pipe/blob/f1cee728d7764846f58ef29d4641f96e6dfb1900/pkg/app/piped/controller/planner.go#L201-L206

Comment (nghialv) [reply pkg/app/piped/controller/planner.go:100]: Right or not. 

Currently, when the planner finished its work (`Run`), the `cancelledCh` will not be used after that.
So in case the piped receives a canceling command immediately after the planner's completion, the controller will be blocked forever.

Comment (nakabonne) [reply pkg/app/piped/controller/planner.go:100]: That makes more sense! Now I can see why using it at this time, thanks :D

**Review by nakabonne — APPROVED** [review]
