### PR TITLE
Return filestore.ErrNotFound when object not found

### LINKED ISSUE #1309: Treat no object case as ErrNotFound
**What happened**:
Currently, minio client gives back no error even if the given object not found when `GetObject` called.

https://github.com/pipe-cd/pipe/blob/24ddc50a39ffd34148c2d460b79632681b1f5c0d/pkg/filestore/minio/minio.go#L102-L105

We should treat as filestore.ErrNotFound like GCS. If we don't, the caller cannot handle it properly:

https://github.com/pipe-cd/pipe/blob/24ddc50a39ffd34148c2d460b79632681b1f5c0d/pkg/filestore/gcs/gcs.go#L86-L91

**What you expected to happen**:

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by sanposhiho**
**What this PR does / why we need it**:

 > Currently, minio client gives back no error even if the given object not found when GetObject called.
We should treat as filestore.ErrNotFound like GCS. If we don't, the caller cannot handle it properly:

**Which issue(s) this PR fixes**:

Fixes #1309 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/filestore/minio/minio.go [hunk 1]
```diff
@@ -100,7 +101,15 @@ func (s *Store) EnsureBucket(ctx context.Context) error {
...
 
 func (s *Store) NewReader(ctx context.Context, path string) (rc io.ReadCloser, err error) {
-	// No error returned even if the object does not exist.
+	_, err = s.client.StatObject(ctx, s.bucket, path, minio.GetObjectOptions{})
+	if err != nil {
+		errRes := minio.ToErrorResponse(err)
+		if errRes.StatusCode == http.StatusNotFound {
+			err = filestore.ErrNotFound
+		}
+		s.logger.Error("failed to create minio object reader", zap.String("path", path), zap.Error(err))
```
Comment (nakabonne) [inline pkg/filestore/minio/minio.go:110]: nit: It would be great if it could be followed our style where must be indented if multiple args given:

```go
	s.logger.Error("failed to create minio object reader",
		zap.String("path", path),
		zap.Error(err),
	)
```

File: pkg/filestore/minio/minio.go [hunk 2]
```diff
@@ -100,7 +101,15 @@ func (s *Store) EnsureBucket(ctx context.Context) error {
...
+		return
+	}
```
Comment (nghialv) [inline pkg/filestore/minio/minio.go:112]:
```suggestion
	if _, err := s.client.StatObject(ctx, s.bucket, path, minio.GetObjectOptions{}); err != nil {
		e := minio.ToErrorResponse(err)
		if e.StatusCode == http.StatusNotFound {
			err = filestore.ErrNotFound
		}
		s.logger.Error("failed to stat minio object", 
			zap.String("path", path),
			zap.Error(err),
		)
		return
	}
```

**Comment by nghialv** [comment]
Thank you.
/approve

File: pkg/filestore/minio/minio.go [hunk 3]
```diff
@@ -100,7 +101,17 @@ func (s *Store) EnsureBucket(ctx context.Context) error {
 }
 
 func (s *Store) NewReader(ctx context.Context, path string) (rc io.ReadCloser, err error) {
-	// No error returned even if the object does not exist.
+	if _, err := s.client.StatObject(ctx, s.bucket, path, minio.GetObjectOptions{}); err != nil {
```
Comment (nghialv) [inline pkg/filestore/minio/minio.go:104]:
```suggestion
	if _, err = s.client.StatObject(ctx, s.bucket, path, minio.GetObjectOptions{}); err != nil {
```
