### PR TITLE
Fix the bug that WAIT stage does not wait for the specified duration

### LINKED ISSUE #1225: In `WAIT` stage in KubernetesApp, do not wait for more than 10 seconds.
**What happened**:
In `WAIT` stage in KubernetesApp, do not wait for more than 10 seconds.

**What you expected to happen**:

wait time specified to `duration` key

**How to reproduce it**:

use bellow `.pipe.yaml`

```
apiVersion: pipecd.dev/v1beta1
kind: KubernetesApp
spec:
  pipeline:
    stages:
      - name: WAIT
        with:
          duration: 60s
```

**Environment**:
- `piped` version: v0.9.0
- `control-plane` version: v0.9.0
- Others: already created Pull Request: #1226

### PR DESCRIPTION
**Pull request by ShotaKitazawa**
**What this PR does / why we need it**:
fix `WAIT` stage in KubernetesApp

**Which issue(s) this PR fixes**:

Fixes #1225

**Does this PR introduce a user-facing change?**:

```release-note
Fix the bug that the WAIT stage does not wait for the specified duration
```

### CODE REVIEW

File: pkg/app/piped/executor/wait/wait.go [hunk 1]
```diff
@@ -83,21 +83,24 @@ func (e *Executor) Execute(sig executor.StopSignal) model.StageStatus {
...
+
+		case s := <-sig.Ch():
+			switch s {
+			case executor.StopSignalCancel:
+				return model.StageStatus_STAGE_CANCELLED
+			case executor.StopSignalTerminate:
+				return originalStatus
+			default:
+				return model.StageStatus_STAGE_FAILURE
+			}
```
Comment (nghialv) [inline pkg/app/piped/executor/wait/wait.go:103]: nit: Could you please change to use a `return` instead of the `break` at line 90.

``` golang
for {
   select {
   case <- timer.C:
      	e.LogPersister.Infof("Waited for %v", totalDuration)
	return model.StageStatus_STAGE_SUCCESS
   
   case <-ticker.C:
        e.LogPersister.Infof("%v elapsed...", time.Since(startTime))

   case s := <-sig.Ch():
        ....
   }
}
}
```

Comment (ShotaKitazawa) [reply pkg/app/piped/executor/wait/wait.go:103]: thanks, I fixed it in `git commit --amend`

**Comment by nghialv** [comment]
@ShotaKitazawa Thank you very much.
/approve
