### PR TITLE
Refine MySQL `find` query builder

### LINKED ISSUE #1735: Wrap queries with `SyncState.Status` field filter as `SyncState` for MySQL datastore
**What would you like to be added**:

**Why is this needed**:

### LINKED ISSUE #1743: Wrap operators for MySQL query
**What happened**:

Currently, `ListFilter` operators used by NoSQL databases (Firestore or MongoDB) such as `==` are unable to be used in case of MySQL as datastore is set.

**What you expected to happen**:

Be able to use `ListFilter` with generic used operators such as `==` for both NoSQL and SQL.

**How to reproduce it**:

**Environment**:
- `piped` version:
- `control-plane` version:
- Others:

### PR DESCRIPTION
**Pull request by khanhtc1202**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1743 
Fixes #1735 

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

File: pkg/datastore/mysql/query.go [hunk 1]
```diff
@@ -93,3 +98,47 @@ func toMySQLDirection(d datastore.OrderDirection) string {
 		return ""
 	}
 }
+
+func refineOrdersField(orders []datastore.Order) []datastore.Order {
+	for i, order := range orders {
+		switch order.Field {
+		case "SyncState.Status":
+			orders[i].Field = "SyncState"
```
Comment (nghialv) [inline pkg/datastore/mysql/query.go:106]: How about converint all "." into "_"?

File: pkg/datastore/mysql/query.go [hunk 2]
```diff
@@ -93,3 +98,47 @@ func toMySQLDirection(d datastore.OrderDirection) string {
...
+		case "==":
+			filters[i].Operator = "="
+		case "in":
+			filters[i].Operator = "IN"
+		case "not-in":
+			filters[i].Operator = "NOT IN"
+		case "!=", ">", ">=", "<", "<=":
+			continue
+		default:
+			err = fmt.Errorf("unsupported operator %s", filter.Operator)
```
Comment (nghialv) [inline pkg/datastore/mysql/query.go:139]: Why not returning here?

File: pkg/datastore/mysql/query.go [hunk 3]
```diff
@@ -93,3 +98,47 @@ func toMySQLDirection(d datastore.OrderDirection) string {
...
+	for i, filter := range filters {
+		switch filter.Operator {
+		case "==":
+			filters[i].Operator = "="
+		case "in":
+			filters[i].Operator = "IN"
+		case "not-in":
+			filters[i].Operator = "NOT IN"
+		case "!=", ">", ">=", "<", "<=":
+			continue
```
Comment (nghialv) [inline pkg/datastore/mysql/query.go:137]: Why not adding?

Comment (khanhtc1202) [reply pkg/datastore/mysql/query.go:137]: I modify the given `filter` itself not creating the new one, so instead of `adding`, those operators are all supported operators, that why we should just leave it as is 😄

File: pkg/datastore/mysql/query.go (hunk 2 above)
Comment (khanhtc1202) [reply pkg/datastore/mysql/query.go:139]: You're right 👍 We should just return err from here 👍

File: pkg/datastore/mysql/query.go (hunk 3 above)
Comment (nghialv) [reply pkg/datastore/mysql/query.go:136]: The function is returning a slice. So we should make a new slice instead of updating the original one.

File: pkg/datastore/mysql/query.go [hunk 4]
```diff
@@ -93,3 +98,45 @@ func toMySQLDirection(d datastore.OrderDirection) string {
...
+		default:
+			continue
+		}
+	}
+	return filters
+}
+
+func refineFiltersOperator(filters []datastore.ListFilter) ([]datastore.ListFilter, error) {
+	for i, filter := range filters {
+		switch filter.Operator {
```
Comment (nghialv) [inline pkg/datastore/mysql/query.go:128]: It is ok for now. But in the future we might define a type for Operator instead of directly using string. Then we have a list of usable operators. Inside each backend package(firestore, mysql) we convert them to the appropriate string.

Comment (khanhtc1202) [reply pkg/datastore/mysql/query.go:128]: Nice idea, will create an issue for that and address it later 👍

File: pkg/datastore/mysql/query.go (hunk 3 above)
Comment (khanhtc1202) [reply pkg/datastore/mysql/query.go:136]: I tend to reduce the cost of allocating new slide (since this one only be used to build string query) but you're right, to not change on the original slide is safer. Let's me change others `refineXXX` functions too.

Comment (khanhtc1202) [reply pkg/datastore/mysql/query.go]: Address on https://github.com/pipe-cd/pipe/pull/1744/commits/7f501806e3cae28577273f3451b84b725ab9cbf6 🙏

**Review by nghialv — APPROVED** [review]
